# MHEALTH dataset

Enlace al dataset: https://archive.ics.uci.edu/dataset/319/mhealth+dataset

In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

In [1]:
data_path = "C:/Users/C-Ramirez/Documents/LCC/RAHBFDP/ProyectoFinal/MHEALTHDATASET"
#data_path = "Aqui pones el tuyo deibi"

In [58]:
test_file = data_path + "/mHealth_subject1.log"
pd.read_csv(test_file, sep="\t", header=None).head()

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
0,-9.8184,0.009971,0.29563,0.004186,0.004186,2.1849,-9.6967,0.63077,0.103900,-0.84053,...,-8.6499,-4.5781,0.187760,-0.44902,-1.0103,0.034483,-2.35000,-1.610200,-0.030899,0
1,-9.8489,0.524040,0.37348,0.004186,0.016745,2.3876,-9.5080,0.68389,0.085343,-0.83865,...,-8.6275,-4.3198,0.023595,-0.44902,-1.0103,0.034483,-2.16320,-0.882540,0.326570,0
2,-9.6602,0.181850,0.43742,0.016745,0.037677,2.4086,-9.5674,0.68113,0.085343,-0.83865,...,-8.5055,-4.2772,0.275720,-0.44902,-1.0103,0.034483,-1.61750,-0.165620,-0.030693,0
3,-9.6507,0.214220,0.24033,0.079540,0.117220,2.1814,-9.4301,0.55031,0.085343,-0.83865,...,-8.6279,-4.3163,0.367520,-0.45686,-1.0082,0.025862,-1.07710,0.006945,-0.382620,0
4,-9.7030,0.303890,0.31156,0.221870,0.205130,2.4173,-9.3889,0.71098,0.085343,-0.83865,...,-8.7008,-4.1459,0.407290,-0.45686,-1.0082,0.025862,-0.53684,0.175900,-1.095500,0

In [59]:
column_names = ["subject","acc_chest_x","acc_chest_y","acc_chest_z", 
    "ecg_l1","ecg_l2", "acc_left_ankle_x", "acc_left_ankle_y", "acc_left_ankle_z", 
    "gyro_left_ankle_x", "gyro_left_ankle_y", "gyro_left_ankle_z", 
    "MAG_left_ankle_x", "MAG_left_ankle_y", "MAG_left_ankle_z",
    "acc_r_lw_arm_x","acc_r_lw_arm_y","acc_r_lw_arm_z",
    "gyro_r_lw_arm_x","gyro_r_lw_arm_y","gyro_r_lw_arm_z",
    "MAG_r_lw_arm_x","MAG_r_lw_arm_y","MAG_r_lw_arm_z",
    "label"
    ]
data = pd.DataFrame(columns=column_names)

In [60]:
for i, file in enumerate(os.listdir(data_path)):
    if file != "README.txt":
        df_tmp = pd.read_csv(os.path.join(data_path, file), header=None, sep="\t")
        df_tmp.columns = column_names[1:]
        df_tmp["subject"] = i+1
        data = pd.concat([data, df_tmp])

C:\Users\C-Ramirez\AppData\Local\Temp\ipykernel_7452\3100880763.py:6: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  data = pd.concat([data, df_tmp])

## Dimensiones del dataset y primeras 5 líneas

In [61]:
data.shape

(1215745, 25)

In [63]:
data.head()

,subject,acc_chest_x,acc_chest_y,acc_chest_z,ecg_l1,ecg_l2,acc_left_ankle_x,acc_left_ankle_y,acc_left_ankle_z,gyro_left_ankle_x,...,acc_r_lw_arm_x,acc_r_lw_arm_y,acc_r_lw_arm_z,gyro_r_lw_arm_x,gyro_r_lw_arm_y,gyro_r_lw_arm_z,MAG_r_lw_arm_x,MAG_r_lw_arm_y,MAG_r_lw_arm_z,label
0,1,-9.8184,0.009971,0.29563,0.004186,0.004186,2.1849,-9.6967,0.63077,0.103900,...,-8.6499,-4.5781,0.187760,-0.44902,-1.0103,0.034483,-2.35000,-1.610200,-0.030899,0
1,1,-9.8489,0.524040,0.37348,0.004186,0.016745,2.3876,-9.5080,0.68389,0.085343,...,-8.6275,-4.3198,0.023595,-0.44902,-1.0103,0.034483,-2.16320,-0.882540,0.326570,0
2,1,-9.6602,0.181850,0.43742,0.016745,0.037677,2.4086,-9.5674,0.68113,0.085343,...,-8.5055,-4.2772,0.275720,-0.44902,-1.0103,0.034483,-1.61750,-0.165620,-0.030693,0
3,1,-9.6507,0.214220,0.24033,0.079540,0.117220,2.1814,-9.4301,0.55031,0.085343,...,-8.6279,-4.3163,0.367520,-0.45686,-1.0082,0.025862,-1.07710,0.006945,-0.382620,0
4,1,-9.7030,0.303890,0.31156,0.221870,0.205130,2.4173,-9.3889,0.71098,0.085343,...,-8.7008,-4.1459,0.407290,-0.45686,-1.0082,0.025862,-0.53684,0.175900,-1.095500,0

## Identifica y elimina datos ausentes

Primero debemos verificar si nuestro dataset tiene presencia o no de datos nulos:

In [62]:
data.isnull().sum()

subject              0
acc_chest_x          0
acc_chest_y          0
acc_chest_z          0
ecg_l1               0
ecg_l2               0
acc_left_ankle_x     0
acc_left_ankle_y     0
acc_left_ankle_z     0
gyro_left_ankle_x    0
gyro_left_ankle_y    0
gyro_left_ankle_z    0
MAG_left_ankle_x     0
MAG_left_ankle_y     0
MAG_left_ankle_z     0
acc_r_lw_arm_x       0
acc_r_lw_arm_y       0
acc_r_lw_arm_z       0
gyro_r_lw_arm_x      0
gyro_r_lw_arm_y      0
gyro_r_lw_arm_z      0
MAG_r_lw_arm_x       0
MAG_r_lw_arm_y       0
MAG_r_lw_arm_z       0
label                0
dtype: int64

En este caso notamos que ninguna columna cuenta con valores nulos, por lo tanto seguimos adelante con el proceso.

## Presenta el resumen estadístico del dataset

In [65]:
print(data.describe())

        acc_chest_x   acc_chest_y   acc_chest_z        ecg_l1        ecg_l2  \
count  1.215745e+06  1.215745e+06  1.215745e+06  1.215745e+06  1.215745e+06
mean  -8.522361e+00 -2.140013e-01 -1.055950e+00 -5.122403e-03 -4.506434e-03
std    4.075293e+00  2.138954e+00  3.574163e+00  7.465971e-01  7.270395e-01
min   -2.243800e+01 -2.018800e+01 -1.840100e+01 -8.619600e+00 -8.619600e+00
25%   -9.804000e+00 -1.272900e+00 -2.867300e+00 -2.344300e-01 -1.883800e-01
50%   -9.311400e+00 -3.538100e-01 -8.702000e-01 -7.116700e-02 -4.186300e-02
75%   -7.637100e+00  7.097800e-01  7.259100e-01  1.590800e-01  1.507100e-01
max    1.909400e+01  2.092700e+01  2.619600e+01  8.514900e+00  8.519100e+00

       acc_left_ankle_x  acc_left_ankle_y  acc_left_ankle_z  \
count      1.215745e+06      1.215745e+06      1.215745e+06
mean       1.494200e+00     -9.692878e+00     -9.548056e-01
std        3.826485e+00      4.171303e+00      5.461803e+00
min       -2.214600e+01     -1.961900e+01     -1.937300e+01
25%        1.413100e-01     -1.020100e+01     -2.649400e+00
50%        1.308900e+00     -9.670300e+00     -1.645600e-02
75%        2.575800e+00     -9.042200e+00      1.301300e+00
max        2.005400e+01      2.116100e+01      2.501500e+01

       gyro_left_ankle_x  gyro_left_ankle_y  ...  MAG_left_ankle_z  \
count       1.215745e+06       1.215745e+06  ...      1.215745e+06
mean       -1.598951e-03      -6.166318e-01  ...     -8.566162e-01
std         4.912172e-01       3.546406e-01  ...      1.768224e+01
min        -2.146600e+00      -7.789900e+00  ...     -2.823900e+02
25%        -4.359900e-01      -8.180100e-01  ...     -2.833100e+00
50%        -1.484200e-02      -7.073200e-01  ...     -4.349900e-01
75%         4.489800e-01      -5.403400e-01  ...      1.976900e+00
max         6.048400e+01       2.011300e+00  ...      2.725600e+02

       acc_r_lw_arm_x  acc_r_lw_arm_y  acc_r_lw_arm_z  gyro_r_lw_arm_x  \
count    1.215745e+06    1.215745e+06    1.215745e+06     1.215745e+06
mean    -3.713413e+00   -5.805526e+00    2.393880e+00    -2.761061e-01
std      4.763586e+00    5.757639e+00    3.876503e+00     5.276888e-01
min     -2.236100e+01   -1.897200e+01   -1.823900e+01    -8.339200e+00
25%     -6.076000e+00   -9.404200e+00    1.296500e-01    -7.058800e-01
50%     -2.977600e+00   -7.461500e+00    1.928100e+00    -3.549000e-01
75%     -1.193700e+00   -2.533900e+00    4.914700e+00     9.607800e-02
max      1.986400e+01    2.219100e+01    2.574100e+01     3.319600e+00

       gyro_r_lw_arm_y  gyro_r_lw_arm_z  MAG_r_lw_arm_x  MAG_r_lw_arm_y  \
count     1.215745e+06     1.215745e+06    1.215745e+06    1.215745e+06
mean     -4.664340e-01     2.666335e-01    1.702138e-01    7.144626e-01
std       5.555510e-01     5.643804e-01    2.667617e+01    3.344453e+01
min      -3.570800e+00    -2.689700e+00   -3.190300e+02   -3.639000e+02
25%      -8.973300e-01    -2.370700e-01   -6.191900e+00   -9.519500e+00
50%      -6.345000e-01     3.017200e-01    3.626200e-01    3.521700e-01
75%      -1.067800e-01     7.780200e-01    6.792300e+00    1.007600e+01
max       1.556500e+00     2.750000e+00    2.511500e+02    3.377600e+02

       MAG_r_lw_arm_z
count    1.215745e+06
mean    -3.668126e-01
std      6.955069e+01
min     -7.175500e+02
25%     -1.423800e+01
50%     -6.729600e-01
75%      1.318600e+01
max      6.571800e+02

[8 rows x 23 columns]

## Distribución de clases

In [71]:
data["label"].value_counts()

label
0     872550
1      30720
2      30720
3      30720
4      30720
9      30720
10     30720
11     30720
5      30720
7      29441
8      29337
6      28315
12     10342
Name: count, dtype: int64